adj1 = input("enter an adjective: ")
adj2 = input("enter another adjective: ")
noun1 = input("enter a noun: ")
noun2 = input("enter another noun: ")
plnoun1 = input("enter a plural noun: ")
game = input("enter a game: ")
plnoun2 = input("enter another plural noun: ")
verbing1 = input("enter a verb ending with 'ing' : ")
verbing2 = input("enter another verb ending with 'ing' : ")
plnoun3 = input("enter another plural noun: ")
verbing3 = input("enter another verb ending with 'ing' : ")
noun3 = input("enter another noun: ")
plant = input("enter a plant: ")
partbody = input("enter a body part: ")
place = input("enter a place: ")
verbing4 = input("enter another verb ending with 'ing' : ")
adj3 = input("enter another adjective: ")
num = input("enter a number: ")
plnoun4 = input("enter another plural noun: ")

print("A vacation is when you take a trip to some",adj1," place with your ",adj2," family.")
print("Usually, you go to some place that is near a/an ",noun1," or up on a/an",noun2,".")
print("A good vacation place is one where you can ride ",plnoun1, " or play ",game," or go hunting for ",plnoun2,".")
print("I like to spend my time ",verbing1," or ",verbing2,".")
print("When parents go on a vacation, they spend their time eating three ",plnoun3, " a day, and fathers play golf, "
                                                                            "and mother sit around ",verbing3,".")
print("Last summer, my little brother fell in a/an ",noun3, " and got poison ",plant," all over his ",partbody,".")
print("My family is going to the ",place,", and I will practice ",verbing4,".")
print("Parents need more vacations than kids as parents are very ",adj3," and because they have to work ",num,
      " hours every day and all year making enough ",plnoun3," to pay for the vacation")
